version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo nothing else to do
artifacts:
  files:
    - '**/*'
  base-directory: dist